name: Release Actions

on:
  release:
    types: [published]

env:
  SOLUTION_FILE_PATH: ISXRI.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Commit ISXRI.dll to release branch
      env:
        GITHUB_TOKEN: ${{ secrets.ISXRIDATA_GITHUB_TOKEN }}
      run: |
        gh auth login --with-token <<< "${{ secrets.ISXRIDATA_GITHUB_TOKEN }}"
        git clone https://github.com/Eq2automation/ISXRI-Data.git
        cd ISXRI-Data
        git checkout -b release
        cp ../path/to/ISXRI.dll .
        git add ISXRI.dll
        git commit -m "Add ISXRI.dll from release"
        git push --set-upstream origin release

    - name: Create pull request
      run: gh pr create -B main -H release --title 'Add ISXRI.dll from release' --body 'Created by GitHub action'
      env:
        GITHUB_TOKEN: ${{ secrets.ISXRIDATA_GITHUB_TOKEN }}

    - name: Merge pull request
      run: |
        PR_NUMBER=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Eq2automation/ISXRI-Data/pulls?head=Eq2automation:release | jq '.[0].number')
        gh pr merge $PR_NUMBER --merge --delete-branch
      env:
        GITHUB_TOKEN: ${{ secrets.ISXRIDATA_GITHUB_TOKEN }}
