name: Release Actions

on:
  release:
    types: [published]

env:
  SOLUTION_FILE_PATH: ISXRI.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Push ISXRI.dll to ISXRI-Data
      env:
        GITHUB_TOKEN: ${{ secrets.ISXRIDATA_GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git clone https://github.com/Eq2automation/ISXRI-Data.git
        cd ISXRI-Data
        git checkout -b isxridll
        cp C:\OneDrive\InnerSpace\x64\Extensions\ISXDK35\ISXRI.dll .
        git add ISXRI.dll
        git commit -m "Add ISXRI.dll"
        git push https://${{ secrets.ISXRIDATA_GITHUB_TOKEN }}@github.com/Eq2automation/ISXRI-Data.git -u isxridll
        gh pr create -B main -H isxridll --title 'Add ISXRI.dll' --body 'Created by GitHub action'
        gh pr merge --merge --delete-branch

    - name: Github Releases To Discord
      uses: SethCohen/github-releases-to-discord@v1.15.0
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        color: "2105893"
        username: "Release Changelog"
        avatar_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"
        footer_title: "Changelog"
        footer_icon_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"
        footer_timestamp: true
