name: Release Actions

on:
  release:
    types: [published]

env:
  SOLUTION_FILE_PATH: ISXRI.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-west-2
        
    - name: Upload artifacts to AWS S3
      uses: usualdesigner/s3-artifact-upload@v1.0.15
      with:
        bucket-name: ${{ secrets.BUCKET_NAME }}
        file: ISXRI.dll
        meta-data: "{x-amz-meta-version,${{ github.ref_name }}}"
